"""remove unit

Revision ID: 25132b8228e8
Revises: caea14f515ca
Create Date: 2026-09-10 17:51:59.534774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25132b8228e8'
down_revision: Union[str, Sequence[str], None] = 'caea14f515ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_item', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_item', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
