"""replace category table with product category enum

Revision ID: 2a17cf716572
Revises: f490bc00d211
Create Date: 2026-09-10 13:55:03.937698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a17cf716572'
down_revision: Union[str, Sequence[str], None] = 'f490bc00d211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. СНЯТЬ ограничения: Сначала удаляем внешний ключ, который держит таблицу
    op.drop_constraint('product_category_id_fkey', 'product', type_='foreignkey')
    
    # 2. УДАЛИТЬ старую колонку, которая ссылалась на этот ключ
    op.drop_column('product', 'category_id')
    
    # 3. ДОБАВИТЬ новую колонку (этот код Alembic сгенерировал сам, он должен быть таким)
    # (Проверь, чтобы тип данных и nullable совпадали с твоей новой моделью)
    op.add_column('product', sa.Column('category', sa.String(length=50), nullable=True))
    
    # 4. И ТОЛЬКО ТЕПЕРЬ, когда связей больше нет, удаляем саму таблицу
    op.drop_table('category')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('product_category_id_fkey'), 'product', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('product', 'category')
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('category_pkey')),
    sa.UniqueConstraint('name', name=op.f('category_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
